# Site settings
title: WebCreate.lk - Beautiful websites
description: 
 Webcreate is a library showcasing beautiful web themes for Wordpress, Joomla, 
 Drupal, ProcessWire and many other CMS and static generators like Jekyll.

# Exclude files
exclude: 
 - CNAME
 - Gemfile
 - Rakefile
 - README.md
 - .gitignore
 - .sass-cache
 - Gemfile.lock

# Site development URL
url: http://webcreate.lk
# url: http://localhost:3000
baseurl: ""

# Build settings
markdown: kramdown
permalink: pretty
highlighter: pygments

# Sass conversion configurations
sass:
 sass_dir: assets/css/_sass
 style: :compressed

webcreate:
  # Google Analytics key, leave blank to ignore
  google_analytics_key: UA-42430656-1